[env:nano_r4]
platform = renesas-ra
board = nano_r4
framework = arduino

monitor_speed = 115200
monitor_filters = time

build_flags =
    -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC

lib_deps =
    arduino-libraries/Servo@^1.2.2
    arduino-libraries/Arduino_LSM6DSOX
    arduino-libraries/Arduino_Modulino